### ISSUE TITLE
Change Content-Type header of gRPC requests

### ISSUE THREAD

**Issue by zvana** [DefGuard/proxy#72]
Would be please possible to set Content-Type header to **application/grpc** or **application/grpc+<message type** (for example: application/grpc+proto)? It's required by Cloudflare for using GRPC with their Proxy -> https://developers.cloudflare.com/network/grpc-connections/

**Comment by teon** [comment]
This should be applied both to:
- [ ] proxy
- [ ] core

**Comment by moubctez** [comment]
`content-type: application/grpc` is the default and it has already been set.
